In [1]:
import numpy as np
np.random.seed(42)
import pandas as pd 
print("libraries imported success")

libraries imported success

In [2]:
n = 5000

# -----------------------------
# DRIVER FEATURES
# -----------------------------

driver_age = np.random.randint(22, 60, n)

driving_hours = np.random.uniform(1, 12, n).round(1)

speed = np.random.randint(35, 110, n)

harsh_braking = np.random.poisson(2, n)

harsh_acceleration = np.random.poisson(2, n)

# Drowsiness increases with driving hours
drowsiness_score = np.clip(
    (driving_hours * 8) + np.random.normal(20, 10, n),
    0,
    100
).round(1)


# -----------------------------
# VEHICLE FEATURES
# -----------------------------

engine_temperature = np.random.normal(92, 8, n).round(1)

engine_vibration = np.random.normal(3.5, 1, n).round(2)

battery_voltage = np.random.normal(12.6, 0.5, n).round(2)

oil_pressure = np.random.normal(42, 8, n).round(1)

tyre_pressure = np.random.normal(33, 3, n).round(1)

vehicle_age = np.random.randint(1, 16, n)

mileage = np.random.randint(50000, 900000, n)

previous_breakdowns = np.random.poisson(1, n)

previous_accidents = np.random.poisson(0.5, n)


# -----------------------------
# ENVIRONMENT FEATURES
# -----------------------------

weather = np.random.choice(
    ["Clear", "Rain", "Fog"],
    n,
    p=[0.60, 0.25, 0.15]
)

road_type = np.random.choice(
    ["Highway", "City", "Mountain"],
    n,
    p=[0.50, 0.30, 0.20]
)


# -----------------------------
# CREATE DATAFRAME
# -----------------------------

df = pd.DataFrame({
    "Driver_Age": driver_age,
    "Driving_Hours": driving_hours,
    "Speed": speed,
    "Harsh_Braking": harsh_braking,
    "Harsh_Acceleration": harsh_acceleration,
    "Drowsiness_Score": drowsiness_score,
    "Engine_Temperature": engine_temperature,
    "Engine_Vibration": engine_vibration,
    "Battery_Voltage": battery_voltage,
    "Oil_Pressure": oil_pressure,
    "Tyre_Pressure": tyre_pressure,
    "Vehicle_Age": vehicle_age,
    "Mileage": mileage,
    "Previous_Breakdowns": previous_breakdowns,
    "Previous_Accidents": previous_accidents,
    "Weather": weather,
    "Road_Type": road_type
})

print("Dataset Generated Successfully ✅")
print("Dataset Shape:", df.shape)

df.head()

Dataset Generated Successfully ✅
Dataset Shape: (5000, 17)

,Driver_Age,Driving_Hours,Speed,Harsh_Braking,Harsh_Acceleration,Drowsiness_Score,Engine_Temperature,Engine_Vibration,Battery_Voltage,Oil_Pressure,Tyre_Pressure,Vehicle_Age,Mileage,Previous_Breakdowns,Previous_Accidents,Weather,Road_Type
0,50,5.4,47,2,1,65.7,83.1,1.76,13.08,59.9,35.5,6,423852,0,0,Clear,Highway
1,36,9.3,69,1,0,100.0,97.2,3.68,11.88,38.0,37.8,13,883857,4,0,Rain,City
2,29,6.0,81,1,2,70.0,93.8,1.98,12.30,50.0,35.3,14,680286,1,0,Clear,Highway
3,42,5.5,62,1,4,62.2,84.9,4.25,12.90,32.4,36.8,4,289202,0,0,Clear,Highway
4,40,11.3,55,0,0,100.0,94.0,4.85,12.56,28.9,33.0,11,172552,1,0,Clear,Highway

In [3]:
## AI Target columns
df.shape

(5000, 17)

In [4]:
# ==========================================
# DRIVER SAFETY RISK SCORE
# ==========================================

driver_score = (
    (df["Driving_Hours"] > 8).astype(int) * 2 +
    (df["Speed"] > 85).astype(int) * 2 +
    (df["Harsh_Braking"] > 3).astype(int) +
    (df["Harsh_Acceleration"] > 3).astype(int) +
    (df["Drowsiness_Score"] > 70).astype(int) * 2 +
    (df["Previous_Accidents"] > 1).astype(int)
)


# ==========================================
# VEHICLE BREAKDOWN RISK SCORE
# ==========================================

breakdown_score = (
    (df["Engine_Temperature"] > 100).astype(int) * 2 +
    (df["Engine_Vibration"] > 5).astype(int) * 2 +
    (df["Battery_Voltage"] < 12).astype(int) +
    (df["Oil_Pressure"] < 30).astype(int) +
    (df["Tyre_Pressure"] < 28).astype(int) +
    (df["Vehicle_Age"] > 10).astype(int) +
    (df["Mileage"] > 600000).astype(int) +
    (df["Previous_Breakdowns"] > 2).astype(int)
)


# ==========================================
# FINAL TARGETS
# ==========================================

df["Driver_Risk"] = np.where(
    driver_score >= 4,
    1,
    0
)

df["Breakdown_Risk"] = np.where(
    breakdown_score >= 4,
    1,
    0
)


print("Target Columns Created Successfully ✅")

print("\nDriver Risk:")
print(df["Driver_Risk"].value_counts())

print("\nBreakdown Risk:")
print(df["Breakdown_Risk"].value_counts())

Target Columns Created Successfully ✅

Driver Risk:
Driver_Risk
0    2980
1    2020
Name: count, dtype: int64

Breakdown Risk:
Breakdown_Risk
0    4641
1     359
Name: count, dtype: int64

In [5]:
df.shape

(5000, 19)

In [6]:
# Save raw dataset

df.to_csv(
    "../data/raw/truck_data.csv",
    index=False
)

print("Dataset Saved Successfully ✅")
print("File: data/raw/truck_data.csv")
print("Shape:", df.shape)

Dataset Saved Successfully ✅
File: data/raw/truck_data.csv
Shape: (5000, 19)

In [7]:
print("========== DATASET INFORMATION ==========\n")

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDriver Risk Distribution:")
print(df["Driver_Risk"].value_counts())

print("\nBreakdown Risk Distribution:")
print(df["Breakdown_Risk"].value_counts())

print("\nFirst 5 Records:")
display(df.head())

========== DATASET INFORMATION ==========

Shape: (5000, 19)

Columns:
['Driver_Age', 'Driving_Hours', 'Speed', 'Harsh_Braking', 'Harsh_Acceleration', 'Drowsiness_Score', 'Engine_Temperature', 'Engine_Vibration', 'Battery_Voltage', 'Oil_Pressure', 'Tyre_Pressure', 'Vehicle_Age', 'Mileage', 'Previous_Breakdowns', 'Previous_Accidents', 'Weather', 'Road_Type', 'Driver_Risk', 'Breakdown_Risk']

Missing Values:
Driver_Age             0
Driving_Hours          0
Speed                  0
Harsh_Braking          0
Harsh_Acceleration     0
Drowsiness_Score       0
Engine_Temperature     0
Engine_Vibration       0
Battery_Voltage        0
Oil_Pressure           0
Tyre_Pressure          0
Vehicle_Age            0
Mileage                0
Previous_Breakdowns    0
Previous_Accidents     0
Weather                0
Road_Type              0
Driver_Risk            0
Breakdown_Risk         0
dtype: int64

Driver Risk Distribution:
Driver_Risk
0    2980
1    2020
Name: count, dtype: int64

Breakdown Risk Distribution:
Breakdown_Risk
0    4641
1     359
Name: count, dtype: int64

First 5 Records:

,Driver_Age,Driving_Hours,Speed,Harsh_Braking,Harsh_Acceleration,Drowsiness_Score,Engine_Temperature,Engine_Vibration,Battery_Voltage,Oil_Pressure,Tyre_Pressure,Vehicle_Age,Mileage,Previous_Breakdowns,Previous_Accidents,Weather,Road_Type,Driver_Risk,Breakdown_Risk
0,50,5.4,47,2,1,65.7,83.1,1.76,13.08,59.9,35.5,6,423852,0,0,Clear,Highway,0,0
1,36,9.3,69,1,0,100.0,97.2,3.68,11.88,38.0,37.8,13,883857,4,0,Rain,City,1,1
2,29,6.0,81,1,2,70.0,93.8,1.98,12.30,50.0,35.3,14,680286,1,0,Clear,Highway,0,0
3,42,5.5,62,1,4,62.2,84.9,4.25,12.90,32.4,36.8,4,289202,0,0,Clear,Highway,0,0
4,40,11.3,55,0,0,100.0,94.0,4.85,12.56,28.9,33.0,11,172552,1,0,Clear,Highway,1,0